[package]
# ToDo: rename this to something that isn't yet used on crates.io
name = "numan"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
